# permissions for end users to view backupsessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupsession-viewer-role
rules:
- apiGroups:
  - restic.metavarse.com
  resources:
  - backupsessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - restic.metavarse.com
  resources:
  - backupsessions/status
  verbs:
  - get
