# permissions for end users to edit backupsessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupsession-editor-role
rules:
- apiGroups:
  - restic.metavarse.com
  resources:
  - backupsessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - restic.metavarse.com
  resources:
  - backupsessions/status
  verbs:
  - get
